services:
  - type: web
    name: stock-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements_render.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
